### ISSUE TITLE
oneOf does not work properly in version 0.96

### ISSUE THREAD

**Issue by ckongEbi** [jhthorsen/json-validator#59] opened 2017-03-23 11:12 UTC
Hi, by upgrading from version 0.92=>0.97, we hit into the error below, which wasn't happening before:

Validation error on evidence line 639 :         $VAR1 = bless( {
                 'path' => '/',
                 'message' => 'allOf failed: allOf failed: All of the oneOf rules match.'
               }, 'JSON::Validator::Error' );

We think it might be a new bug, this is the schema we use

https://github.com/opentargets/json_schema/blob/master/src/evidence/base.json#L24 

and a single line of our json data, thanks.

{"disease": {"name": "breast adenocarcinoma", "source_name": "breast adenocarcinoma", "id": "http://www.ebi.ac.uk/efo/EFO_0000304"}, "sourceID": "eva_somatic", "target": {"activity": "http://identifiers.org/cttv.activity/damaging_to_target", "id": "http://identifiers.org/ensembl/ENSG00000023287", "target_type": "http://identifiers.org/cttv.target/gene_variant"}, "literature": {"references": [{"lit_id": "http://europepmc.org/abstract/MED/12068296"}]}, "evidence": {"urls": [{"nice_name": "Further details in ClinVar database", "url": "http://www.ncbi.nlm.nih.gov/clinvar/RCV000004183"}], "date_asserted": "2016-10-03T00:00:00", "known_mutations": [{"preferred_name": "splice_acceptor_variant", "functional_consequence": "http://purl.obolibrary.org/obo/SO_0001574"}], "evidence_codes": ["http://purl.obolibrary.org/obo/ECO_0000205"], **_"resource_score": {"type": "probability", "value": 1},_** "is_associated": true, "provenance_type": {"database": {"version": "1.0", "dbxref": {"version": "2015-04", "id": "http://identifiers.org/clinvar", "url": "http://identifiers.org/clinvar.record/RCV000004183"}, "id": "EVA"}, "expert": {"statement": "Primary submitter of data", "status": true}, "literature": {"references": [{"lit_id": "http://europepmc.org/abstract/MED/12068296"}]}}}, "unique_association_fields": {"phenotype": "http://www.ebi.ac.uk/efo/EFO_0000304", "clinvarAccession": "RCV000004183", "gene": "ENSG00000023287", "alleleOrigin": "somatic"}, "validated_against_schema_version": "1.2.5", "type": "somatic_mutation", "access_level": "public"}

**Comment by jhthorsen** [comment] 2017-03-23 21:15
Thanks for reporting in.

Could you help me help you? If so, can you do this:

* Make a smaller test case. the schema you link to is quite hard to go through and doesn't make a good failing test.
* Upgrade one version of a time and let me know when it started failing? This can be done using the command:
```
cpanm https://github.com/jhthorsen/json-validator/archive/0.93.tar.gz
cpanm https://github.com/jhthorsen/json-validator/archive/0.94.tar.gz
...
cpanm https://github.com/jhthorsen/json-validator/archive/0.97.tar.gz
```

**Comment by ckongEbi** [comment] 2017-03-24 16:41
@jhthorsen yes, but i think the archive link is not working, please have a look. 

Cheers

**Comment by ckongEbi** [comment] 2017-04-19 13:57
@jhthorsen what i've located is that the issue appear to be introduced in 0.96. 0.95 runs fine without issue. 

0.96 2017-03-06T20:53:35+0100
 - Fix JSON::Validator::load_and_validate_schema()
 - Add handling of header/formData/query as array #38
 - Allow alternative date-time separator #49
 - Improved recursion tracking #52
 - More tests in t/acceptance.t are ok #52
 - Avoid loading the same file multiple times #54
 - Swagger2 is deprecated

**Comment by jhthorsen** [comment] 2017-04-19 14:16
What about a smaller test case?

**Comment by ckongEbi** [comment] 2017-04-19 14:50
Example an extract of the JSON file,

    "resource_score": {
      "value": 1,
      "type": "probability"
    },

which corresponds to this schema, does this helps?

https://github.com/opentargets/json_schema/blob/master/src/evidence/association_score/probability.json

**Comment by jhthorsen** [comment] 2017-04-19 15:00
Not really. I don't see any "oneOf" in that schema.

**Comment by ckongEbi** [comment] 2017-04-19 15:03
Please see this 
https://github.com/opentargets/json_schema/blob/master/src/evidence/base.json
which is parent of the former..

**Comment by wbazant** [comment] 2017-06-12 15:10
@jhthorsen 
Here is a smaller case : [out.txt](https://github.com/jhthorsen/json-validator/files/1068603/out.txt)
as an output of this program (with a debug flag on):
```
my $validator = JSON::Validator->new;
$validator->schema($schemaUri);
print STDOUT Dumper($validator->{"schema"});
```

I had a go at debugging why this happens but the furthest I got is that in 
https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator.pm#L298
`$look_in = $self->_load_schema($ref, $namespace);` is fine, and then `look_in` gets overwritten with the other entry in the next line `$look_in = $self->_resolve_schema($look_in, $look_in->data->{id} || $namespace);`

**Comment by jhthorsen** [comment] 2017-06-12 18:53
What do you mean with "$look_in is fine"? Is "fine" the same as a "true" value..? If that is the case, how can it go into the `if (!$look_in)` block?

**Comment by wbazant** [comment] 2017-06-16 21:29
@jhthorsen sorry I haven't linked very precisely let me try improve the writeup of this issue.
L299 `$look_in = $self->_load_schema($ref, $namespace);` is the last thing that I think executes correctly. $look_in is falsey after L297, goes into the conditions, is fine - by which I mean that when I look at the dump of that variable, it looks like the Perl version of the JSON object that represents the schema. After L300 executes, this is no longer the case - the dump of $look_in is mangled - all the array entries for where oneOf is become the same. Then after I let the snippet finish, the final output is wrong in the same way.

I squinted at the program for a while to see how it can happen but was thwarted by my lack of Perl skill.

Again, to reproduce:
```
my $validator = JSON::Validator->new;
$validator->schema("https://github.com/opentargets/json_schema/blob/master/src/evidence/base.json");
print STDOUT Dumper($validator->{"schema"});
```

**Comment by wbazant** [comment] 2017-09-13 16:00
I think the cause of error is the same as #65 - I was super confused when writing the above but also observed the schema loaded up being incorrect. I propose to merge this issue with #59.

**Comment by jhthorsen** [comment] 2017-10-10 19:09
I'm closing this after the commit from @khvzak. Please re-open if that didn't help. (Remember to test from "master" branch and not from CPAN)

**Closed by jhthorsen** 2017-10-10 19:09 UTC
Labels: bug, help wanted
